name: cloakery CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    name: Validation (Lint, TypeCheck, Test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Lint & Format (Biome)
        run: npx @biomejs/biome ci .

      - name: Type Check (TSC)
        run: npx tsc --noEmit

      # TODO: add tests here:
      # - name: Run Tests
      #   run: npm test

  validate-cd:
    name: Validate CD (OIDC Trust)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-1

      - name: Verify Identity
        run: aws sts get-caller-identity

  deploy-stage:
    name: Deploy to Staging
    needs: [validate, validate-cd]
    if: github.event_name == 'pull_request'
    permissions:
      id-token: write # Required to pass OIDC permission to reusable workflow
      contents: read
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      stage: dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

  deploy-prod:
    name: Deploy to Production
    needs: [validate, validate-cd]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      id-token: write # Required to pass OIDC permission to reusable workflow
      contents: read
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      stage: prod
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
