name: Reusable Deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      domain:
        required: true
        type: string
      domain_certificate_arn:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      SERVERLESS_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: Deploy (${{ inputs.stage }})
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-1

      - name: Serverless Deploy
        id: deploy
        run: npx serverless deploy --stage ${{ inputs.stage }} --param="domain=${{ inputs.domain }}" --param="domain_certificate_arn=${{ inputs.domain_certificate_arn }}"
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Query Outputs
        id: query_outputs
        run: |
          # Use AWS CLI to query outputs from the CloudFormation stack
          STACK_NAME=cloakery-${{ inputs.stage }}
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='StaticSiteBucketName'].OutputValue" --output text)
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
          
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "distribution_id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT

      - name: Deploy Static Site
        run: |
          aws s3 sync ./public s3://${{ steps.query_outputs.outputs.bucket_name }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ steps.query_outputs.outputs.distribution_id }} --paths "/*"
